---
resources:
- name: dockerfile-repo
  type: git
  source:
   uri: http://gogs:3000/student/lab-assets
   branch: master

- name: golang-image
  type: docker-image
  source:
    repository: dockerregistry:5000/student/golang-image
    insecure_registries: ["dockerregistry:5000"]

jobs:
- name: build-image
  plan:
  - get: dockerfile-repo
  - put: golang-image
    params: {build: dockerfile-repo}
    get_params: {rootfs: true}