---
resources:
- name: dockerfile-repo
  type: git
  source:
   uri: ((dockerfile-git-uri))
   branch: master

- name: cli-code
  type: git
  source:
    uri: ((yml2env-git-uri))
    branch: master

- name: release-candidate
  type: s3
  source: 
    endpoint: minio1:9000
    disable_ssl: true
    bucket: release-candidates
    regexp: yml2env-(.*)
    # access_key_id: access_key
    # secret_access_key: secret_access_key
    access_key_id: ((password))
    secret_access_key: ((s3secret))

- name: test-report
  type: s3
  source: 
    endpoint: minio1:9000
    disable_ssl: true
    bucket: test-reports
    regexp: junit-(.*).xml
    access_key_id: ((password))
    secret_access_key: ((s3secret))

- name: golang-image
  type: docker-image
  source: ((docker-registry-source))

- name: send-email
  type: email
  source: 
    from: bishwajit.samanta@mailsac.com

resource_types:
- name: email
  type: docker-image
  source:
    repository: mdomke/concourse-email-resource

jobs:
- name: build-image
  plan:
  - get: dockerfile-repo
  - put: golang-image
    params: 
      build: dockerfile-repo
    get_params: 
      rootfs: true

- name: compile
  plan: 
  - get: cli-code
  - get: golang-image
    trigger: true
    passed: 
    - build-image
  - task: go-build
    image: golang-image
    config:
      platform: linux
      # Tell Concourse which things to mount into the container
      inputs:
      - name: cli-code
      outputs:
      - name: built-binary
      
      run:
        path: /bin/sh
        args:
        - -xc
        - |
          mkdir -p src/github.com/EngineerBetter/yml2env
          mv cli-code/* src/github.com/EngineerBetter/yml2env
          export GOPATH=$PWD
          cd src/github.com/EngineerBetter/yml2env
          go build -o $OLDPWD/built-binary/yml2env-$(date +%s)

  - put: release-candidate
    params:
      file: built-binary/yml2env-*

- name: test
  plan: 
  - get: cli-code
  - get: golang-image
    trigger: true
    passed: 
    - compile
  - task: test
    config:
      platform: linux
      # Define the Docker image to use as the filesystem for this task
      image_resource:
        type: docker-image
        source: 
          repository: dockerregistry:5000/student/golang-image
          insecure_registries: ["dockerregistry:5000"]
      # Tell Concourse which things to mount into the container
      inputs:
      - name: cli-code
        path: gopath/src/github.com/EngineerBetter/yml2env

      params:
        FIXTURE_LOCATION: fixtures/
        FLAKE: anyvalue/

      outputs:
      - name: built-binary
      - name: test-report

      run:
        path: gopath/src/github.com/EngineerBetter/yml2env/test.sh

# Config and on_failure should be in the same indentation

    on_failure:
      do:
      - put: send-email
        params: 
          to: 
          - bishwajit.samanta@mailsac.com
          subject_text: subject
          body_text: body
          
      - put: test-report
        params: 
          file: test-report/junit-*.xml
        